apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-mongo-0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
