apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myflix-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-nginx        # Must match your Deployment Name
  minReplicas: 1          # Never go below 1
  maxReplicas: 10         # Never go above 10 (Safety cap)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Target 50% CPU usage
